apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
  labels:
    name: wireguard
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: wg-configmap
  namespace: wireguard
data:
  wg0.conf: |
    [Interface]
    Address = 10.25.187.1/24
    ListenPort = 51820
    PrivateKey = 
    SaveConfig = false
    MTU = 1280
    PostUp = iptables -t mangle -A POSTROUTING -p tcp --tcp-flags SYN,RST SYN -o eth0 -j TCPMSS --clamp-mss-to-pmtu
    PostUp = iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    PostUp = iptables -A FORWARD -i %i -j ACCEPT
    PostDown = iptables -D FORWARD -i %i -j ACCEPT
    PostDown = iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
    PostDown = iptables -t mangle -D POSTROUTING -p tcp --tcp-flags SYN,RST SYN -o eth0 -j TCPMSS --clamp-mss-to-pmtu
    PostUp = sysctl -q -w net.ipv4.ip_forward=1
    PostDown = sysctl -q -w net.ipv4.ip_forward=0
    [Peer]
    PublicKey = 
    PresharedKey = 
    AllowedIPs = 10.25.187.10/32
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  namespace: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      nodeSelector:
        hehe: node01
      initContainers:
        - name: sysctls
          image: busybox
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
      containers:
        - name: wireguard
          image: masipcat/wireguard-go:latest
          ports:
          - containerPort: 51820
            protocol: UDP
            name: wireguard
          env:
          - name: LOG_LEVEL
            value: info
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
          resources:
            requests:
              memory: 64Mi
              cpu: "100m"
            limits:
              memory: 256Mi
          volumeMounts:
          - name: cfgmap
            mountPath: /etc/wireguard/wg0.conf
            subPath: wg0.conf
      volumes:
      - name: cfgmap
        configMap:
          name: wg-configmap
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: wg-ingress
  namespace: wireguard
spec:
  rules:
  - host: "{{ .Values.FQDN }}"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wg-service
            port:
              number: 51820
---
kind: Service
apiVersion: v1
metadata:
  name: wg-service
  namespace: wireguard
  labels:
    app: wireguard
spec:
  type: LoadBalancer
  ports:
  - name: wg
    protocol: UDP
    port: 51820
    targetPort: 51820
  selector:
    app: wg-app